const valid_vaccinations = [
  'Adenovirus',
  'Anthrax',
  'Cholera',
  'DTaP',
  'DT',
  'Haemophilus influenzae type b (Hib)',
  'Hepatitis A',
  'Hepatitis B',
  'Herpes Zoster (Shingles)',
  'Human Papillomavirus (HPV)',
  'Influenza',
  'Japanese encephalitis',
  'Measles, Mumps, Rubella',
  'Meningococcal',
  'Pneumococcal',
  'Polio',
  'Rabies',
  'Rotavirus',
  'Tetanus, (reduced) Diphtheria',
  'Tetanus, (reduced) Diphtheria, (reduced) Pertussis',
  'Typhoid',
  'Varicella',
  'Vaccinia (Smallpox)',
  'Yellow Fever',
  'DTaP, Polio',
  'DTaP, hepatitis B, Polio',
  'DTaP, Polio, Haemophilus influenzae type b',
  'Hepatitis A, Hepatitis B',
  'Measles, Mumps, Rubella, Varicella',
  'COVID-19',
];
console.table(valid_vaccinations);
